#:kivy 1.9.0

<RV>:
    viewclass: "MyBox"
    RecycleBoxLayout:
        default_size: None, 200
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
        

    
    
<MyBox@BoxLayout>:
    active: stored_state.active
    orientation: 'vertical'
    Label:
        id: lbsA
        text: str(root.link)
    Button:
        text: "w"
        #on_press: root.on_press()
    